name: Character Sheet

# This action works with pull requests and pushes
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: write-all

jobs:
  sheet_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Build HTML from Jinja template
        run: |
          pushd tools
            pip install -r requirements.txt
            python build.py
          popd

      - name: Prepare artifact
        run: |
          cp -r static/* release                    
          zip -r character_sheet-release-latest.zip release

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{json,html}
          github_token: ${{ secrets.PT_GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: character-sheet-artifact
          path: ${{ github.workspace}}/release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            ${{ github.workspace}}/character_sheet-release-latest.zip
